import "./globals.css";
import { Inter } from "next/font/google";
import { routeLinks } from "@/utils/routes";
import Link from "next/link";
import ThemeProvider from "@/components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Money_loans",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <header>
          <ThemeProvider />
          <section>
            <p>Hola soy el heroSection</p>
          </section>
        </header>
        <main>{children}</main>
        <footer>
          <p>Hola soy el footer</p>
        </footer>
      </body>
    </html>
  );
}
